-- phpMyAdminで実行してください
-- データベース名: yatagarasu_db（config.phpに合わせて変更可）

CREATE TABLE IF NOT EXISTS `bukken` (
  `id`              INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `kanri_bangou`    VARCHAR(20)  DEFAULT NULL COMMENT '管理番号',
  `bukken_mei`      VARCHAR(100) NOT NULL     COMMENT '物件名',
  `category`        VARCHAR(50)  DEFAULT NULL COMMENT 'カテゴリー',
  `bukken_shurui`   VARCHAR(50)  DEFAULT NULL COMMENT '物件種目',
  `yoto`            VARCHAR(100) DEFAULT NULL COMMENT '用途',
  `shozaichi`       VARCHAR(200) DEFAULT NULL COMMENT '所在地',
  `rosen`           VARCHAR(100) DEFAULT NULL COMMENT '路線',
  `moyori_eki`      VARCHAR(50)  DEFAULT NULL COMMENT '最寄り駅',
  `toho_fun`        TINYINT UNSIGNED DEFAULT NULL COMMENT '徒歩（分）',
  `yachin`          INT UNSIGNED DEFAULT NULL COMMENT '家賃/賃料（円）',
  `shohizei`        INT UNSIGNED DEFAULT NULL COMMENT '消費税（円）',
  `kyoekihi`        VARCHAR(50)  DEFAULT NULL COMMENT '共益費/管理費',
  `shikikin`        INT UNSIGNED DEFAULT NULL COMMENT '敷金（円）',
  `reikin`          INT UNSIGNED DEFAULT NULL COMMENT '礼金（円）',
  `menseki_m2`      DECIMAL(7,2) DEFAULT NULL COMMENT '面積（㎡）',
  `tsubo`           DECIMAL(7,2) DEFAULT NULL COMMENT '坪数',
  `shozai_kai`      VARCHAR(20)  DEFAULT NULL COMMENT '所在階',
  `madori`          VARCHAR(30)  DEFAULT NULL COMMENT '間取り',
  `kozo_kibo`       VARCHAR(100) DEFAULT NULL COMMENT '構造規模',
  `chikunen_tsuki`  VARCHAR(20)  DEFAULT NULL COMMENT '築年月',
  `keiyaku_kikan`   VARCHAR(30)  DEFAULT NULL COMMENT '契約期間',
  `jido_koshin`     VARCHAR(10)  DEFAULT NULL COMMENT '自動更新',
  `chushajo`        VARCHAR(50)  DEFAULT NULL COMMENT '駐車場',
  `hontai_setsubi`  VARCHAR(200) DEFAULT NULL COMMENT '本体設備',
  `kakuko_setsubi`  VARCHAR(200) DEFAULT NULL COMMENT '各戸設備',
  `hosho_gaisha`    VARCHAR(200) DEFAULT NULL COMMENT '保証会社',
  `hoken`           VARCHAR(200) DEFAULT NULL COMMENT '保険',
  `joken`           TEXT         DEFAULT NULL COMMENT '条件',
  `torihiki_yosu`   VARCHAR(30)  DEFAULT NULL COMMENT '取引態様',
  `tesuryo`         VARCHAR(50)  DEFAULT NULL COMMENT '手数料',
  `annai_hoho`      VARCHAR(200) DEFAULT NULL COMMENT '案内方法',
  `biko`            TEXT         DEFAULT NULL COMMENT '備考',
  `keisai_date`     DATE         DEFAULT NULL COMMENT '掲載日',
  `kakunin_date`    DATE         DEFAULT NULL COMMENT '確認日',
  `kanri_gaisha`    VARCHAR(100) DEFAULT NULL COMMENT '管理会社',
  `created_at`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物件データベース';